// generated by Fast Light User Interface Designer (fluid) version 1.0311
// manually added header includes
#include "shelfsight_gui.h"
#include "shelfsight_gui.h"
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Menu_Item.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_PNG_Image.H>      
// ----- forward declarations for all callbacks -------------------------------
static void add_books(Fl_Widget*, void*);
static void edit_books(Fl_Widget*, void*);
static void remove_books(Fl_Widget*, void*);
static void manage_categories(Fl_Widget*, void*);
static void add_readers(Fl_Widget*, void*);
static void edit_readers(Fl_Widget*, void*);
static void remove_readers(Fl_Widget*, void*);
static void import_readers(Fl_Widget*, void*);
static void add_loans(Fl_Widget*, void*);
static void edit_loans(Fl_Widget*, void*);
static void remove_loans(Fl_Widget*, void*);
static void expired_loans(Fl_Widget*, void*);
static void backup_offline(Fl_Widget*, void*);
static void backup_directconnection(Fl_Widget*, void*);
static void backup_localp2p(Fl_Widget*, void*);
static void backup_onlinep2p(Fl_Widget*, void*);
static void settings_account(Fl_Widget*, void*);
static void settings_theme(Fl_Widget*, void*);
static void settings_performance(Fl_Widget*, void*);
static void settings_networking(Fl_Widget*, void*);
static void settings_other(Fl_Widget*, void*);
static void saveasdefault_selectdb(Fl_Widget*, void*);
static void saveascustom_selectdb(Fl_Widget*, void*);
static void loadasdefault_selectdb(Fl_Widget*, void*);
static void loadascustom_selectdb(Fl_Widget*, void*);
static void verifybookdb_selectdb(Fl_Widget*, void*);
static void verifyreaderdb_selectdb(Fl_Widget*, void*);
static void verifyloandb_selectdb(Fl_Widget*, void*);
static void login_show(Fl_Widget*, void*);
static void register_show(Fl_Widget*, void*);
static void clear_workspace(Fl_Widget*, void*);
