Use the widget’s user‑data field instead of the two global maps.
Each widget stores an identifier (or a small struct) in its own user‑data, and the single callback reads that value to decide what to do.
cpp

/* --------------------------------------------------------------
   1️⃣  Define the identifiers (or a struct) that will be stored
   -------------------------------------------------------------- */
enum WidgetId {
    ID_LOGIN = 1,
    ID_QUIT,
    ID_OPEN_DB,
    ID_SAVE,
    // …add more as needed
};

/* --------------------------------------------------------------
   2️⃣  Optional: a small struct when a widget needs extra data
   -------------------------------------------------------------- */
struct LoginData {
    Fl_Input* user;
    Fl_Input* pwd;
};

/* --------------------------------------------------------------
   3️⃣  Generic callback – it looks at the widget’s user‑data
   -------------------------------------------------------------- */
static void generic_handler(Fl_Widget* w, void*) {
    // The user‑data is a void* that we interpret according to the id
    void* ud = w->user_data();

    // First byte can hold the enum value (cast back to int)
    int id = reinterpret_cast<intptr_t>(ud) & 0xFFFFFFFF;

    switch (id) {
        case ID_LOGIN: {
            // For the login button we stored a pointer to LoginData
            LoginData* ld = static_cast<LoginData*>(w->user_data());
            const char* user = ld->user->value();
            const char* pwd  = ld->pwd->value();

            bool ok = verify_login(user, pwd);
            fl_message(ok ? "Login succeeded" : "Invalid credentials");
            if (!ok) ld->pwd->value("");
            break;
        }

        case ID_QUIT:
            Fl::delete_widget(Fl::first_window());
            break;

        case ID_OPEN_DB: {
            Fl_File_Browser* fb = static_cast<Fl_File_Browser*>(w);
            fl_message("Chosen DB: %s", fb->value());
            break;
        }

        case ID_SAVE:
            fl_message("Save button pressed");
            // …your save logic here…
            break;

        default:
            fl_message("Clicked: %s", w->label());
            break;
    }
}

/* --------------------------------------------------------------
   4️⃣  Wire‑up the widgets – store the id (and any extra data) as
       user‑data before attaching the callback
   -------------------------------------------------------------- */
static void wire_up_all() {
    /* ----------  LOGIN BUTTON  ---------- */
    static LoginData loginInfo = { inp_user, inp_pwd };
    btn_login->user_data(&loginInfo);          // store struct (its address also encodes the id)
    btn_login->callback(generic_handler);

    /* ----------  QUIT BUTTON  ---------- */
    btn_quit->user_data(reinterpret_cast<void*>(static_cast<intptr_t>(ID_QUIT)));
    btn_quit->callback(generic_handler);

    /* ----------  FILE BROWSER  ---------- */
    flbrw_bookdb_selectdb->user_data(reinterpret_cast<void*>(static_cast<intptr_t>(ID_OPEN_DB)));
    flbrw_bookdb_selectdb->callback(generic_handler);

    /* ----------  SAVE BUTTON  ---------- */
    btn_save->user_data(reinterpret_cast<void*>(static_cast<intptr_t>(ID_SAVE)));
    btn_save->callback(generic_handler);
}

/* --------------------------------------------------------------
   5️⃣  Main – same as before
   -------------------------------------------------------------- */
int main(int argc, char **argv) {
    Fl::args(argc, argv);
    Fl_Double_Window* win = make_window();   // generated by Fluid
    wire_up_all();                           // register everything
    return Fl::run();
}

How it works

    User‑data as identifier – Fl_Widget::user_data() holds a void*.
    For widgets that need no extra data we store the enum value directly, casting it to a pointer (`reinterpret_cast<void*>(static_cast<intptr_t>(ID_QUIT))
    User‑data as struct – For widgets that need extra pointers (e.g., the login button) we allocate a small struct (LoginData) and store its address. The struct’s first field can still be the enum if you prefer a unified layout, but the example simply uses the struct pointer and extracts the fields directly.
    Single callback – generic_handler reads the widget’s own user‑data, decides which case to run, and accesses any auxiliary data that was stored together with the identifier.

Adding a new widget

    Create an enum entry (ID_NEW).
    If extra data is needed, define a struct and allocate a static instance (or heap‑allocate if lifetime matters).
    cpp

    static NewData nd = { … };
    btn_new->user_data(&nd);

    If no extra data, just store the enum value:
    cpp

    btn_new->user_data(reinterpret_cast<void*>(static_cast<intptr_t>(ID_NEW)));

    Add a case for ID_NEW in generic_handler.
    Call `callback(generic_handler.

All widgets now differentiate themselves by the user‑data they carry, eliminating the need for the two global maps while keeping the same flexibility.
