#include <tcl.h>
#include <tk.h>

#include <zlib.h>

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <string>
#include <vector>

// generated by pack.py
extern "C" const size_t EMBEDDED_RAW_SIZE;
extern "C" const size_t EMBEDDED_GZ_SIZE;
extern "C" const unsigned char EMBEDDED_GZ[];

// GUI layout inside the embedded payload (set by the build script).
#ifndef SHELF_APP_DIR
#define SHELF_APP_DIR "app"
#endif
#ifndef SHELF_MAIN
#define SHELF_MAIN "app.tcl"
#endif

// C++ library shims (from libshelf.a)
extern "C" int add_ints(int, int);
extern "C" const char* shelf_today(void);
extern "C" const char* shelf_add_days(const char*, int);

namespace {

std::string cache_root()
{
    if (const char* e = std::getenv("EMBED_ROOT")) return e;
    const char* home = std::getenv("HOME");
    if (!home || !*home) home = "/tmp";
    if (const char* xdg = std::getenv("XDG_CACHE_HOME")) {
        return std::string(xdg) + "/ShelfSight_tcl";
    }
    return std::string(home) + "/.cache/ShelfSight_tcl";
}

// Decompress EMBEDDED_GZ into an in-memory directory map.
std::map<std::string, std::string> unpack()
{
    std::map<std::string, std::string> files;
    std::vector<unsigned char> raw(EMBEDDED_RAW_SIZE);
    uLongf dst = EMBEDDED_RAW_SIZE;
    if (uncompress(raw.data(), &dst, EMBEDDED_GZ, EMBEDDED_GZ_SIZE) != Z_OK ||
        dst != EMBEDDED_RAW_SIZE) {
        return files;
    }
    const unsigned char* p = raw.data();
    const unsigned char* end = p + raw.size();
    uint32_t count;
    if (p + 4 > end) return files;
    std::memcpy(&count, p, 4);
    p += 4;
    for (uint32_t i = 0; i < count; ++i) {
        uint32_t nl, dl;
        if (p + 8 > end) break;
        std::memcpy(&nl, p, 4);
        std::memcpy(&dl, p + 4, 4);
        p += 8;
        if (p + nl + dl > end) break;
        std::string name(reinterpret_cast<const char*>(p), nl);
        files[name] = std::string(reinterpret_cast<const char*>(p + nl), dl);
        p += nl + dl;
    }
    return files;
}

bool write_file(const std::string& path, const std::string& data)
{
    std::ofstream out(path, std::ios::binary | std::ios::trunc);
    if (!out) return false;
    out.write(data.data(), static_cast<std::streamsize>(data.size()));
    return static_cast<bool>(out);
}

int EmbedRootCmd(ClientData, Tcl_Interp* ip, int objc, Tcl_Obj* const objv[])
{
    if (objc != 1) {
        Tcl_WrongNumArgs(ip, 1, objv, "");
        return TCL_ERROR;
    }
    std::map<std::string, std::string> files = unpack();
    if (files.empty()) {
        Tcl_SetObjResult(ip, Tcl_NewStringObj(
            "embedded payload missing or corrupt", -1));
        return TCL_ERROR;
    }
    const std::string root = cache_root();
    for (const auto& kv : files) {
        std::string full = root + "/" + kv.first;
        std::string dir = full.substr(0, full.find_last_of('/'));
        std::string cmd = "file mkdir [list " + dir + "]";
        if (Tcl_Eval(ip, cmd.c_str()) != TCL_OK) return TCL_ERROR;
        if (!write_file(full, kv.second)) {
            Tcl_SetObjResult(ip,
                Tcl_NewStringObj("cannot write embedded file", -1));
            return TCL_ERROR;
        }
    }
    Tcl_SetObjResult(ip, Tcl_NewStringObj(root.c_str(), -1));
    return TCL_OK;
}

int CmdAddInts(ClientData, Tcl_Interp* ip, int objc, Tcl_Obj* const objv[])
{
    if (objc != 3) {
        Tcl_WrongNumArgs(ip, 1, objv, "a b");
        return TCL_ERROR;
    }
    int a, b;
    if (Tcl_GetIntFromObj(ip, objv[1], &a) != TCL_OK) return TCL_ERROR;
    if (Tcl_GetIntFromObj(ip, objv[2], &b) != TCL_OK) return TCL_ERROR;
    Tcl_SetObjResult(ip, Tcl_NewIntObj(add_ints(a, b)));
    return TCL_OK;
}

int CmdShelfToday(ClientData, Tcl_Interp* ip, int objc, Tcl_Obj* const objv[])
{
    if (objc != 1) {
        Tcl_WrongNumArgs(ip, 1, objv, "");
        return TCL_ERROR;
    }
    const char* s = shelf_today();
    Tcl_SetObjResult(ip, Tcl_NewStringObj(s, -1));
    std::free(const_cast<char*>(s));
    return TCL_OK;
}

int CmdShelfAddDays(ClientData, Tcl_Interp* ip, int objc,
                    Tcl_Obj* const objv[])
{
    if (objc != 3) {
        Tcl_WrongNumArgs(ip, 1, objv, "date days");
        return TCL_ERROR;
    }
    int days;
    if (Tcl_GetIntFromObj(ip, objv[2], &days) != TCL_OK) return TCL_ERROR;
    const char* r =
        shelf_add_days(Tcl_GetString(objv[1]), days);
    Tcl_SetObjResult(ip, Tcl_NewStringObj(r, -1));
    std::free(const_cast<char*>(r));
    return TCL_OK;
}

}  // namespace

int main(int argc, char** argv)
{
    Tcl_FindExecutable(argv[0]);
    Tcl_Interp* ip = Tcl_CreateInterp();
    if (Tcl_Init(ip) != TCL_OK) {
        fprintf(stderr, "Tcl_Init: %s\n", Tcl_GetStringResult(ip));
        return 1;
    }
    if (Tk_Init(ip) != TCL_OK) {
        fprintf(stderr, "Tk_Init: %s\n", Tcl_GetStringResult(ip));
        return 1;
    }

    Tcl_CreateObjCommand(ip, "embed_root", EmbedRootCmd, NULL, NULL);
    Tcl_CreateObjCommand(ip, "add_ints", CmdAddInts, NULL, NULL);
    Tcl_CreateObjCommand(ip, "shelf_today", CmdShelfToday, NULL, NULL);
    Tcl_CreateObjCommand(ip, "shelf_add_days", CmdShelfAddDays, NULL, NULL);

    Tcl_SetVar2(ip, "argv0", NULL, argv[0], TCL_GLOBAL_ONLY);
    std::string argc_str = std::to_string(argc - 1);
    Tcl_SetVar2(ip, "argc", NULL, argc_str.c_str(), TCL_GLOBAL_ONLY);
    std::string argv_list = "{" + std::string(argc > 1 ? argv[1] : "") + "}";
    for (int i = 2; i < argc; ++i) {
        argv_list += " {" + std::string(argv[i]) + "}";
    }
    Tcl_SetVar2(ip, "argv", NULL, argv_list.c_str(), TCL_GLOBAL_ONLY);

    const std::string bootstrap =
        std::string("wm withdraw .\n"
        "namespace eval ::ShelfSight {}\n"
        "set root [embed_root]\n"
        "set ::ShelfSight::root $root\n"
        "lappend auto_path $root\n"
        "rename exec ::tcl::__shelfsight_exec\n"
        "proc ::exec args {\n"
        "    if {[lindex $args 0] eq \"wish\"} { return }\n"
        "    uplevel 1 ::tcl::__shelfsight_exec $args\n"
        "}\n"
        "if {[catch {source [file join $root " SHELF_APP_DIR " " SHELF_MAIN "]} err]} {\n"
        "    rename ::exec {}\n"
        "    rename ::tcl::__shelfsight_exec ::exec\n"
        "    puts stderr \"startup error: $err\"\n"
        "    exit 1\n"
        "}\n"
        "rename ::exec {}\n"
        "rename ::tcl::__shelfsight_exec ::exec\n");

    int rc = Tcl_Eval(ip, bootstrap.c_str());
    if (rc != TCL_OK) {
        fprintf(stderr, "bootstrap: %s\n", Tcl_GetStringResult(ip));
        return 1;
    }

    Tk_MainLoop();
    Tcl_DeleteInterp(ip);
    return 0;
}
