#!/usr/bin/env python3
"""Pack a set of directories into embedded_data.cpp for the single-exe build.

Usage:
    python3 pack.py <out.cpp> <dir1> [dir2 ...]

Every regular file under each <dirN> is stored relative to that dir and
embedded into the generated C++ as one gzip-compressed blob.

Blob layout (little-endian):
    u32 count
    repeat count times:
        u32 name_len, u32 data_len, name bytes, data bytes
"""
import os
import struct
import sys
import zlib


def main():
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 1
    out_cpp, dirs = sys.argv[1], sys.argv[2:]

    entries = []
    for root in dirs:
        root = os.path.abspath(root)
        prefix = os.path.basename(root.rstrip(os.sep))
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = sorted(d for d in dirnames if d != ".git")
            for f in sorted(filenames):
                full = os.path.join(dirpath, f)
                rel = prefix + "/" + os.path.relpath(full, root)
                with open(full, "rb") as fh:
                    data = fh.read()
                entries.append((rel, data))

    body = struct.pack("<I", len(entries))
    for name, data in entries:
        body += struct.pack("<II", len(name.encode()), len(data))
        body += name.encode()
        body += data

    raw_size = len(body)
    compressed = zlib.compress(body, 9)

    lines = []
    lines.append("// generated by pack.py -- do not edit")
    lines.append("#include <cstddef>")
    lines.append("#include <cstdint>")
    lines.append(f"extern const size_t EMBEDDED_RAW_SIZE = {raw_size};")
    lines.append(f"extern const size_t EMBEDDED_GZ_SIZE = {len(compressed)};")
    lines.append("extern const unsigned char EMBEDDED_GZ[] = {")
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i + 16]
        lines.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")

    with open(out_cpp, "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"packed {len(entries)} files ({raw_size} bytes raw, "
          f"{len(compressed)} compressed) -> {out_cpp}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
