// generated by Fast Light User Interface Designer (fluid) version 1.0311

#include "shelfsight_gui.h"

Fl_Double_Window *window_assistant=(Fl_Double_Window *)0;

Fl_Image *assistant_image=(Fl_Image *)0;

Fl_Menu_Button *mnubtn_books=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_books[] = {
 {"Add Books", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(add_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Books", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(edit_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Books", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(remove_books), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Manage Categories", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(manage_categories), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_readers=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_readers[] = {
 {"Add Readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(add_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(edit_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(remove_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Import readers", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(import_readers), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_loans=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_loans[] = {
 {"Add Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(add_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(edit_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(remove_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Expired Loans", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(expired_loans), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_databases=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_databases[] = {
 {"Load Default DBs", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Select current DBs", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Backup", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Offline", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_offline), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Online", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Direct connection", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_directconnection), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Local peer-to-peer (LAN)", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_localp2p), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Online peer-to-peer (internet)", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(backup_onlinep2p), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"Manage", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Add Database", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit Database", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_settings=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_settings[] = {
 {"Account", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_account), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Theme", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_theme), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Performance", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_performance), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Networking", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_networking), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Other", 0,  (Fl_Callback*)MENU_BTN_CB, (void*)(settings_other), 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_login=(Fl_Menu_Button *)0;

Fl_Menu_Button *mnubtn_register=(Fl_Menu_Button *)0;

Fl_Menu_Button *menubtn_clear=(Fl_Menu_Button *)0;

Fl_Group *group_register=(Fl_Group *)0;

Fl_Input *inp_usr_reg=(Fl_Input *)0;

Fl_Input *inp_pwd1_reg=(Fl_Input *)0;

Fl_Input *inp_pwd2_reg=(Fl_Input *)0;

Fl_Input_Choice *cic_role_reg=(Fl_Input_Choice *)0;

Fl_Button *btn_reg_reg=(Fl_Button *)0;

Fl_Button *btn_clear_reg=(Fl_Button *)0;

Fl_Button *btn_back_reg=(Fl_Button *)0;

Fl_Check_Button *chk_showpwd_reg=(Fl_Check_Button *)0;

Fl_Button *btn_help_reg=(Fl_Button *)0;

Fl_Group *group_login=(Fl_Group *)0;

Fl_Input *inp_usr_log=(Fl_Input *)0;

Fl_Input *inp_pwd_log=(Fl_Input *)0;

Fl_Check_Button *chk_showpwd_log=(Fl_Check_Button *)0;

Fl_Button *btn_login_log=(Fl_Button *)0;

Fl_Button *btn_cls_log=(Fl_Button *)0;

Fl_Button *btn_back_log=(Fl_Button *)0;

Fl_Button *btn_help_log=(Fl_Button *)0;

Fl_Group *group_addbooks=(Fl_Group *)0;

Fl_Input *inp_title_addbk=(Fl_Input *)0;

Fl_Input *inp_id_addbk=(Fl_Input *)0;

Fl_Input *inp_author_addbk=(Fl_Input *)0;

Fl_Button *btn_checkitle_addbk=(Fl_Button *)0;

Fl_Button *btn_checkauthor_addbk=(Fl_Button *)0;

Fl_Button *btn_checkid_addbk=(Fl_Button *)0;

Fl_Check_Button *chk_nonnumeric_addbk=(Fl_Check_Button *)0;

Fl_Check_Button *chk_automaticallycheckid_addbk=(Fl_Check_Button *)0;

Fl_Choice *cic_category_addbk=(Fl_Choice *)0;

Fl_Choice *cic_status_addbk=(Fl_Choice *)0;

Fl_Button *btn_addbook_addbk=(Fl_Button *)0;

Fl_Button *btn_undoadd_addbk=(Fl_Button *)0;

Fl_Input *inp_search_addbk=(Fl_Input *)0;

Fl_Choice *cic_searchby_addbk=(Fl_Choice *)0;

Fl_Button *btn_search_addbk=(Fl_Button *)0;

Fl_Browser *brw_search_addbk=(Fl_Browser *)0;

Fl_Button *btn_help_addbk=(Fl_Button *)0;

Fl_Group *group_addreaders=(Fl_Group *)0;

Fl_Input *inp_name_addrdr=(Fl_Input *)0;

Fl_Button *btn_name_addrdr=(Fl_Button *)0;

Fl_Input *inp_surname_addrdr=(Fl_Input *)0;

Fl_Input *inp_grade_addrdr=(Fl_Input *)0;

Fl_Button *btn_checksurname_addrdr=(Fl_Button *)0;

Fl_Input *inp_class_addrdr=(Fl_Input *)0;

Fl_Input *inp_readerid_addrdr=(Fl_Input *)0;

Fl_Check_Button *chk_nonnumeric_addrdr=(Fl_Check_Button *)0;

Fl_Check_Button *chk_automaticallycheckid_addrdr=(Fl_Check_Button *)0;

Fl_Button *checkid_addrdr=(Fl_Button *)0;

Fl_Button *btn_addreader_addrdr=(Fl_Button *)0;

Fl_Button *btn_undolastadd_addrdr=(Fl_Button *)0;

Fl_Choice *cic_searchby_addrdr=(Fl_Choice *)0;

Fl_Button *btn_search_addrdr=(Fl_Button *)0;

Fl_Browser *brw_search_addrdr=(Fl_Browser *)0;

Fl_Input *inp_search_addrdr=(Fl_Input *)0;

Fl_Button *btn_help_addrdr=(Fl_Button *)0;

Fl_Group *group_addloans=(Fl_Group *)0;

Fl_Input *inp_bookid_addlns=(Fl_Input *)0;

Fl_Choice *cic_searchby_addlns=(Fl_Choice *)0;

Fl_Button *btn_search_addlns=(Fl_Button *)0;

Fl_Browser *brw_search_addlns=(Fl_Browser *)0;

Fl_Input *inp_search_addlns=(Fl_Input *)0;

Fl_Choice *cic_searchwhat_addlns=(Fl_Choice *)0;

Fl_Input *inp_readerid_addlns=(Fl_Input *)0;

Fl_Input *inp_loanid_addlns=(Fl_Input *)0;

Fl_Input *inp_expirydate_addlns=(Fl_Input *)0;

Fl_Check_Button *chk_generate_addlns=(Fl_Check_Button *)0;

Fl_Button *btn_addloan_addlns=(Fl_Button *)0;

Fl_Button *btn_undolastadd_addlns=(Fl_Button *)0;

Fl_Button *btn_help_addlns=(Fl_Button *)0;

Fl_Group *group_editbooks=(Fl_Group *)0;

Fl_Input *inp_searchterm_editbk=(Fl_Input *)0;

Fl_Choice *cic_searchby_editbk=(Fl_Choice *)0;

Fl_Button *btn_search_editbk=(Fl_Button *)0;

Fl_Browser *brw_search_editbk=(Fl_Browser *)0;

Fl_Button *btn_help_editbk=(Fl_Button *)0;

Fl_Input *inp_title_editbk=(Fl_Input *)0;

Fl_Button *btn_checktitle_editbk=(Fl_Button *)0;

Fl_Input *inp_author_editbk=(Fl_Input *)0;

Fl_Input *inp_bookid_editbk=(Fl_Input *)0;

Fl_Button *btn_checkauthor_editbk=(Fl_Button *)0;

Fl_Button *btn_checktitle_editbk=(Fl_Button *)0;

Fl_Check_Button *chk_nonnumeric_editbk=(Fl_Check_Button *)0;

Fl_Check_Button *chk_automaticallycheck_editbk=(Fl_Check_Button *)0;

Fl_Choice *cic_category_editbk=(Fl_Choice *)0;

Fl_Choice *cic_status_editbk=(Fl_Choice *)0;

Fl_Button *btn_editbook_editbk=(Fl_Button *)0;

Fl_Button *btn_undolastedit_editbk=(Fl_Button *)0;

Fl_Group *group_deletebooks=(Fl_Group *)0;

Fl_Input *inp_search_delbks=(Fl_Input *)0;

Fl_Choice *cic_searchby_delbks=(Fl_Choice *)0;

Fl_Button *btn_search_delbks=(Fl_Button *)0;

Fl_Browser *brw_search_delbks=(Fl_Browser *)0;

Fl_Button *btn_help_delbks=(Fl_Button *)0;

Fl_Input *inp_bookid_delbks=(Fl_Input *)0;

Fl_Button *btn_deletebook_delbks=(Fl_Button *)0;

Fl_Button *btn_undolastdelete_delbks=(Fl_Button *)0;

Fl_Browser *brw_searchdeleted_delbks=(Fl_Browser *)0;

Fl_Button *btn_restoreselected_delbks=(Fl_Button *)0;

Fl_Button *btn_searchdeleted_delbks=(Fl_Button *)0;

Fl_Group *group_editreaders=(Fl_Group *)0;

Fl_Input *inp_readername_editrdr=(Fl_Input *)0;

Fl_Button *btn_checkname_editrdr=(Fl_Button *)0;

Fl_Input *inp_readersurname_editrdr=(Fl_Input *)0;

Fl_Input *inp_grade_editrdr=(Fl_Input *)0;

Fl_Button *btn_checksurname_editrdr=(Fl_Button *)0;

Fl_Input *inp_class_editrdr=(Fl_Input *)0;

Fl_Input *inp_readerid_editrdr=(Fl_Input *)0;

Fl_Check_Button *chk_nonnumeric_editrd=(Fl_Check_Button *)0;

Fl_Check_Button *chk_automaticallycheckid_editrdr=(Fl_Check_Button *)0;

Fl_Button *btn_checkid_editrdr=(Fl_Button *)0;

Fl_Button *btn_editreader_editrdr=(Fl_Button *)0;

Fl_Button *btn_undolastadd_editrdr=(Fl_Button *)0;

Fl_Choice *cic_searchby_editrdr=(Fl_Choice *)0;

Fl_Button *btn_search_editrdr=(Fl_Button *)0;

Fl_Browser *brw_search_editrdr=(Fl_Browser *)0;

Fl_Input *inp_search_editrdr=(Fl_Input *)0;

Fl_Button *btn_help_editrdr=(Fl_Button *)0;

Fl_Group *group_deletereaders=(Fl_Group *)0;

Fl_Input *inp_search_delrdr=(Fl_Input *)0;

Fl_Choice *cic_searchby_delrdr=(Fl_Choice *)0;

Fl_Button *btn_search_delrdr=(Fl_Button *)0;

Fl_Browser *brw_search_delrdr=(Fl_Browser *)0;

Fl_Input *inp_readerid_delrdr=(Fl_Input *)0;

Fl_Button *btn_deletereader_delrdr=(Fl_Button *)0;

Fl_Button *btn_undolastdelete_delrdr=(Fl_Button *)0;

Fl_Browser *brw_deleted_delrdr=(Fl_Browser *)0;

Fl_Button *btn_restoreselected_delrdr=(Fl_Button *)0;

Fl_Group *group_editloans=(Fl_Group *)0;

Fl_Input *inp_bookid_editlns=(Fl_Input *)0;

Fl_Choice *cic_searchby_editlns=(Fl_Choice *)0;

Fl_Button *btn_search_editlns=(Fl_Button *)0;

Fl_Browser *brw_search_editlns=(Fl_Browser *)0;

Fl_Input *inp_search_editlns=(Fl_Input *)0;

Fl_Choice *cic_searchwhat_editlns=(Fl_Choice *)0;

Fl_Input *inp_readerid_editlns=(Fl_Input *)0;

Fl_Input *inp_loanid_editlns=(Fl_Input *)0;

Fl_Check_Button *chk_autogenerate_editlns=(Fl_Check_Button *)0;

Fl_Input *inp_expirydate_editlns=(Fl_Input *)0;

Fl_Button *btn_editloans_editlns=(Fl_Button *)0;

Fl_Button *btn_undolastedit_editlns=(Fl_Button *)0;

Fl_Button *btn_help_editlns=(Fl_Button *)0;

Fl_Group *group_markloans=(Fl_Group *)0;

Fl_Choice *cic_searchby_marklns=(Fl_Choice *)0;

Fl_Button *btn_search_marklns=(Fl_Button *)0;

Fl_Browser *brw_select_marklns=(Fl_Browser *)0;

Fl_Input *inp_search_marklns=(Fl_Input *)0;

Fl_Choice *cic_searchwhat_marklns=(Fl_Choice *)0;

Fl_Button *btn_help_marklns=(Fl_Button *)0;

Fl_Input *inp_prolongby_marklns=(Fl_Input *)0;

Fl_Button *btn_prolong_marklns=(Fl_Button *)0;

Fl_Button *btn_markreturned_marklns=(Fl_Button *)0;

Fl_Button *btn_marklost_marklns=(Fl_Button *)0;

Fl_Group *group_backdrop=(Fl_Group *)0;

Fl_Clock *clk_time_backdrop=(Fl_Clock *)0;

Fl_Group *group_selectdb=(Fl_Group *)0;

Fl_File_Browser *flbrw_bookdb_selectdb=(Fl_File_Browser *)0;

Fl_File_Browser *flbrw_readerdb_selectdb=(Fl_File_Browser *)0;

Fl_File_Browser *flbrw_loandb_selectdb=(Fl_File_Browser *)0;

Fl_Menu_Button *mnubtn_saveconfig_selectdb=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_saveconfig_selectdb[] = {
 {"Save as Default", 0,  (Fl_Callback*)BTN_CB, (void*)(saveasdefault_selectdb), 0, (uchar)FL_NORMAL_LABEL, 0, 15, 0},
 {"Save as Custom", 0,  (Fl_Callback*)BTN_CB, (void*)(saveascustom_selectdb), 0, (uchar)FL_NORMAL_LABEL, 0, 15, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *mnubtn_loadconfig_selectdb=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_loadconfig_selectdb[] = {
 {"Load as Default", 0,  (Fl_Callback*)BTN_CB, (void*)(loadasdefault_selectdb), 0, (uchar)FL_NORMAL_LABEL, 0, 15, 0},
 {"Load as Custom", 0,  (Fl_Callback*)BTN_CB, (void*)(loadascustom_selectdb), 0, (uchar)FL_NORMAL_LABEL, 0, 15, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Button *btn_back_selectdb=(Fl_Button *)0;

Fl_Button *btn_setselected_selectdb=(Fl_Button *)0;

Fl_Menu_Button *mnubtn_verifydb_selectdb=(Fl_Menu_Button *)0;

Fl_Menu_Item menu_mnubtn_verifydb_selectdb[] = {
 {"Verify Book DB", 0,  (Fl_Callback*)BTN_CB, (void*)(verifybookdb_selectdb), 0, (uchar)FL_NORMAL_LABEL, 0, 15, 0},
 {"Verify Reader DB", 0,  (Fl_Callback*)BTN_CB, (void*)(verifyreaderdb_selectdb), 0, (uchar)FL_NORMAL_LABEL, 0, 15, 0},
 {"Verify Loan DB", 0,  (Fl_Callback*)BTN_CB, (void*)(verifyloandb_selectdb), 0, (uchar)FL_NORMAL_LABEL, 0, 15, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Double_Window* make_window() {
  { window_assistant = new Fl_Double_Window(421, 166, "Merlin the Mole - your assistant");
    { Fl_Text_Display* o = new Fl_Text_Display(0, 0, 10, 25, "Merlin the Mole");
      o->labelsize(21);
      o->align(Fl_Align(FL_ALIGN_RIGHT));
    } // Fl_Text_Display* o
    { // The image of the agent
      assistant_image = new Fl_Image(0, 25, 145, 135);
      assistant_image->box(FL_NO_BOX);
      assistant_image->color(FL_BACKGROUND_COLOR);
      assistant_image->selection_color(FL_BACKGROUND_COLOR);
      assistant_image->labeltype(FL_NORMAL_LABEL);
      assistant_image->labelfont(0);
      assistant_image->labelsize(14);
      assistant_image->labelcolor(FL_FOREGROUND_COLOR);
      assistant_image->align(Fl_Align(FL_ALIGN_CENTER));
      assistant_image->when(FL_WHEN_RELEASE);
    } // Fl_Image* assistant_image
    { Fl_Input* o = new Fl_Input(145, 140, 190, 25, "Your question:");
      o->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Input* o
    { Fl_Button* o = new Fl_Button(335, 140, 85, 25, "Submit");
      o->labelsize(16);
    } // Fl_Button* o
    { new Fl_Text_Display(160, 15, 255, 110, "Answer");
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(360, 0, 55, 15, "Close");
      o->color((Fl_Color)41);
    } // Fl_Button* o
    window_assistant->end();
  } // Fl_Double_Window* window_assistant
  { Fl_Double_Window* o = new Fl_Double_Window(542, 358, "ShelfSight");
    w = o; if (w) {/* empty */}
    { mnubtn_books = new Fl_Menu_Button(0, 0, 55, 25, "Books");
      mnubtn_books->menu(menu_mnubtn_books);
    } // Fl_Menu_Button* mnubtn_books
    { mnubtn_readers = new Fl_Menu_Button(55, 0, 70, 25, "Readers");
      mnubtn_readers->menu(menu_mnubtn_readers);
    } // Fl_Menu_Button* mnubtn_readers
    { mnubtn_loans = new Fl_Menu_Button(125, 0, 60, 25, "Loans");
      mnubtn_loans->menu(menu_mnubtn_loans);
    } // Fl_Menu_Button* mnubtn_loans
    { mnubtn_databases = new Fl_Menu_Button(185, 0, 85, 25, "Databases");
      mnubtn_databases->menu(menu_mnubtn_databases);
    } // Fl_Menu_Button* mnubtn_databases
    { mnubtn_settings = new Fl_Menu_Button(270, 0, 65, 25, "Settings");
      mnubtn_settings->menu(menu_mnubtn_settings);
    } // Fl_Menu_Button* mnubtn_settings
    { mnubtn_login = new Fl_Menu_Button(335, 0, 80, 25, "Log in/out");
      mnubtn_login->callback((Fl_Callback*)MENU_BTN_CB, (void*)(login_show));
    } // Fl_Menu_Button* mnubtn_login
    { mnubtn_register = new Fl_Menu_Button(415, 0, 75, 25, "Register");
      mnubtn_register->callback((Fl_Callback*)MENU_BTN_CB, (void*)(register_show));
    } // Fl_Menu_Button* mnubtn_register
    { // Clears workspace - shows backdrop
      menubtn_clear = new Fl_Menu_Button(485, 0, 55, 25, "Clear");
      menubtn_clear->callback((Fl_Callback*)MENU_BTN_CB, (void*)(clear_workspace));
    } // Fl_Menu_Button* menubtn_clear
    { // Register
      group_register = new Fl_Group(0, 25, 540, 335);
      group_register->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(195, 25, 155, 0, "Register");
        o->labelsize(41);
        o->align(Fl_Align(34));
      } // Fl_Text_Display* o
      { inp_usr_reg = new Fl_Input(105, 95, 435, 30, "Username");
        inp_usr_reg->labelsize(19);
      } // Fl_Input* inp_usr_reg
      { inp_pwd1_reg = new Fl_Input(105, 135, 435, 30, "Password");
        inp_pwd1_reg->labelsize(19);
      } // Fl_Input* inp_pwd1_reg
      { inp_pwd2_reg = new Fl_Input(120, 170, 420, 30, "Password again");
      } // Fl_Input* inp_pwd2_reg
      { cic_role_reg = new Fl_Input_Choice(325, 200, 195, 65, "Role");
        cic_role_reg->color((Fl_Color)34);
        cic_role_reg->selection_color((Fl_Color)34);
        cic_role_reg->labelsize(31);
        cic_role_reg->textsize(21);
      } // Fl_Input_Choice* cic_role_reg
      { btn_reg_reg = new Fl_Button(375, 290, 155, 70, "Register");
        btn_reg_reg->color((Fl_Color)25);
        btn_reg_reg->selection_color((Fl_Color)35);
        btn_reg_reg->labelsize(31);
        btn_reg_reg->callback((Fl_Callback*)BTN_CB, (void*)(REG));
      } // Fl_Button* btn_reg_reg
      { btn_clear_reg = new Fl_Button(190, 290, 180, 70, "Clear");
        btn_clear_reg->color((Fl_Color)25);
        btn_clear_reg->selection_color((Fl_Color)35);
        btn_clear_reg->labelsize(31);
        btn_clear_reg->callback((Fl_Callback*)BTN_CB, (void*)(CLS));
      } // Fl_Button* btn_clear_reg
      { btn_back_reg = new Fl_Button(5, 290, 180, 70, "Back");
        btn_back_reg->color((Fl_Color)25);
        btn_back_reg->selection_color((Fl_Color)27);
        btn_back_reg->labelsize(31);
        btn_back_reg->callback((Fl_Callback*)BTN_CB, (void*)(BACK));
      } // Fl_Button* btn_back_reg
      { chk_showpwd_reg = new Fl_Check_Button(15, 200, 35, 40, "Show password");
        chk_showpwd_reg->down_box(FL_DOWN_BOX);
        chk_showpwd_reg->labelsize(25);
        chk_showpwd_reg->callback((Fl_Callback*)BTN_CB, (void*)(showpwd_reg));
      } // Fl_Check_Button* chk_showpwd_reg
      { btn_help_reg = new Fl_Button(5, 30, 65, 30, "HELP");
        btn_help_reg->labelsize(25);
        btn_help_reg->callback((Fl_Callback*)BTN_CB, (void*)(HELP_REG));
      } // Fl_Button* btn_help_reg
      group_register->end();
      Fl_Group::current()->resizable(group_register);
    } // Fl_Group* group_register
    { // Login
      group_login = new Fl_Group(0, 25, 540, 340);
      group_login->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(200, 30, 155, 0, "Login");
        o->labelsize(41);
        o->align(Fl_Align(34));
      } // Fl_Text_Display* o
      { inp_usr_log = new Fl_Input(110, 90, 425, 30, "Username");
        inp_usr_log->labelsize(19);
      } // Fl_Input* inp_usr_log
      { inp_pwd_log = new Fl_Input(110, 125, 425, 30, "Password");
        inp_pwd_log->labelsize(19);
      } // Fl_Input* inp_pwd_log
      { chk_showpwd_log = new Fl_Check_Button(20, 175, 25, 25, "Show password");
        chk_showpwd_log->down_box(FL_DOWN_BOX);
        chk_showpwd_log->labelsize(31);
        chk_showpwd_log->callback((Fl_Callback*)BTN_CB, (void*)(showpwd_log));
      } // Fl_Check_Button* chk_showpwd_log
      { btn_login_log = new Fl_Button(365, 230, 175, 130, "LOGIN");
        btn_login_log->color((Fl_Color)25);
        btn_login_log->selection_color((Fl_Color)35);
        btn_login_log->labelsize(31);
        btn_login_log->callback((Fl_Callback*)BTN_CB, (void*)(LOGIN));
      } // Fl_Button* btn_login_log
      { btn_cls_log = new Fl_Button(180, 230, 180, 130, "Clear");
        btn_cls_log->color((Fl_Color)25);
        btn_cls_log->selection_color((Fl_Color)35);
        btn_cls_log->labelsize(31);
        btn_cls_log->callback((Fl_Callback*)BTN_CB, (void*)(CLS));
      } // Fl_Button* btn_cls_log
      { btn_back_log = new Fl_Button(10, 230, 160, 130, "Back");
        btn_back_log->color((Fl_Color)25);
        btn_back_log->selection_color((Fl_Color)35);
        btn_back_log->labelsize(31);
        btn_back_log->callback((Fl_Callback*)BTN_CB, (void*)(BACK));
      } // Fl_Button* btn_back_log
      { btn_help_log = new Fl_Button(5, 30, 75, 35, "HELP");
        btn_help_log->labelsize(21);
        btn_help_log->callback((Fl_Callback*)BTN_CB, (void*)(HELP_LOG));
      } // Fl_Button* btn_help_log
      group_login->end();
    } // Fl_Group* group_login
    { // Add Books
      group_addbooks = new Fl_Group(0, 25, 540, 335);
      group_addbooks->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(165, 25, 10, 30, "Add Books");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_title_addbk = new Fl_Input(50, 60, 410, 30, "Title");
        inp_title_addbk->labelsize(21);
      } // Fl_Input* inp_title_addbk
      { inp_id_addbk = new Fl_Input(85, 120, 160, 30, "Book ID");
        inp_id_addbk->labelsize(21);
      } // Fl_Input* inp_id_addbk
      { inp_author_addbk = new Fl_Input(75, 90, 385, 30, "Author");
        inp_author_addbk->labelsize(21);
      } // Fl_Input* inp_author_addbk
      { // Checks if title already exists
        btn_checkitle_addbk = new Fl_Button(460, 60, 80, 30, "Check Title");
        btn_checkitle_addbk->callback((Fl_Callback*)BTN_CB, (void*)(checktitle_addbk));
      } // Fl_Button* btn_checkitle_addbk
      { // Check if author already exists
        btn_checkauthor_addbk = new Fl_Button(460, 90, 80, 30, "Check Author");
        btn_checkauthor_addbk->labelsize(12);
        btn_checkauthor_addbk->callback((Fl_Callback*)BTN_CB, (void*)(checkauthor_addbk));
      } // Fl_Button* btn_checkauthor_addbk
      { // Checks f ID already exists
        btn_checkid_addbk = new Fl_Button(460, 120, 80, 30, "Check ID");
        btn_checkid_addbk->callback((Fl_Callback*)BTN_CB, (void*)(checkid-addbk));
      } // Fl_Button* btn_checkid_addbk
      { chk_nonnumeric_addbk = new Fl_Check_Button(370, 120, 90, 30, "Non-numeric");
        chk_nonnumeric_addbk->down_box(FL_DOWN_BOX);
        chk_nonnumeric_addbk->labelsize(12);
        chk_nonnumeric_addbk->callback((Fl_Callback*)BTN_CB, (void*)(nonnumeric_addbk));
      } // Fl_Check_Button* chk_nonnumeric_addbk
      { chk_automaticallycheckid_addbk = new Fl_Check_Button(240, 120, 125, 30, "Automatically check ID");
        chk_automaticallycheckid_addbk->down_box(FL_DOWN_BOX);
        chk_automaticallycheckid_addbk->labelsize(12);
        chk_automaticallycheckid_addbk->callback((Fl_Callback*)BTN_CB, (void*)(automaticallycheckid-addbk));
      } // Fl_Check_Button* chk_automaticallycheckid_addbk
      { cic_category_addbk = new Fl_Choice(65, 150, 200, 25, "Category");
        cic_category_addbk->down_box(FL_BORDER_BOX);
        cic_category_addbk->callback((Fl_Callback*)BTN_CB, (void*)(category_addbk));
      } // Fl_Choice* cic_category_addbk
      { cic_status_addbk = new Fl_Choice(315, 150, 225, 25, "Status");
        cic_status_addbk->down_box(FL_BORDER_BOX);
        cic_status_addbk->callback((Fl_Callback*)BTN_CB, (void*)(status_addbk));
      } // Fl_Choice* cic_status_addbk
      { btn_addbook_addbk = new Fl_Button(225, 175, 315, 40, "ADD BOOK");
        btn_addbook_addbk->labelsize(21);
        btn_addbook_addbk->callback((Fl_Callback*)BTN_CB, (void*)(ADDBOOK));
      } // Fl_Button* btn_addbook_addbk
      { btn_undoadd_addbk = new Fl_Button(5, 175, 210, 40, "Undo last add");
        btn_undoadd_addbk->labelsize(21);
        btn_undoadd_addbk->callback((Fl_Callback*)BTN_CB, (void*)(undoadd_addbk));
      } // Fl_Button* btn_undoadd_addbk
      { Fl_Text_Display* o = new Fl_Text_Display(205, 215, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_search_addbk = new Fl_Input(95, 245, 235, 30, "Search term:");
        inp_search_addbk->labelsize(16);
      } // Fl_Input* inp_search_addbk
      { cic_searchby_addbk = new Fl_Choice(330, 245, 105, 25, "Search by:");
        cic_searchby_addbk->down_box(FL_BORDER_BOX);
        cic_searchby_addbk->labelsize(17);
        cic_searchby_addbk->callback((Fl_Callback*)BTN_CB, (void*)(searchby_addbk));
        cic_searchby_addbk->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_addbk
      { btn_search_addbk = new Fl_Button(435, 225, 105, 45, "SEARCH");
        btn_search_addbk->labelsize(21);
        btn_search_addbk->callback((Fl_Callback*)BTN_CB, (void*)(search_addbk));
      } // Fl_Button* btn_search_addbk
      { // Search results, click to fill text fields
        brw_search_addbk = new Fl_Browser(5, 270, 535, 90);
        brw_search_addbk->callback((Fl_Callback*)BTN_CB, (void*)(browser_addbk));
      } // Fl_Browser* brw_search_addbk
      { btn_help_addbk = new Fl_Button(0, 30, 70, 30, "HELP");
        btn_help_addbk->labelsize(21);
        btn_help_addbk->callback((Fl_Callback*)BTN_CB, (void*)(HELP_ADDBK));
      } // Fl_Button* btn_help_addbk
      group_addbooks->end();
    } // Fl_Group* group_addbooks
    { // Add Readers
      group_addreaders = new Fl_Group(-10, 25, 555, 345);
      group_addreaders->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(150, 25, 10, 30, "Add Readers");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_name_addrdr = new Fl_Input(60, 60, 380, 30, "Name");
        inp_name_addrdr->labelsize(21);
      } // Fl_Input* inp_name_addrdr
      { btn_name_addrdr = new Fl_Button(440, 60, 100, 30, "Check Name");
        btn_name_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(checkname_addrdr));
      } // Fl_Button* btn_name_addrdr
      { inp_surname_addrdr = new Fl_Input(70, 90, 370, 30, "Surname");
        inp_surname_addrdr->labelsize(16);
      } // Fl_Input* inp_surname_addrdr
      { inp_grade_addrdr = new Fl_Input(45, 120, 20, 30, "Grade");
        inp_grade_addrdr->labelsize(15);
      } // Fl_Input* inp_grade_addrdr
      { btn_checksurname_addrdr = new Fl_Button(440, 90, 100, 30, "Check Surname");
        btn_checksurname_addrdr->labelsize(12);
        btn_checksurname_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(checksurname_addrdr));
      } // Fl_Button* btn_checksurname_addrdr
      { inp_class_addrdr = new Fl_Input(110, 120, 20, 30, "Class");
        inp_class_addrdr->labelsize(15);
      } // Fl_Input* inp_class_addrdr
      { inp_readerid_addrdr = new Fl_Input(200, 120, 105, 30, "Reader ID");
        inp_readerid_addrdr->labelsize(15);
      } // Fl_Input* inp_readerid_addrdr
      { chk_nonnumeric_addrdr = new Fl_Check_Button(305, 140, 90, 30, "Non-numeric");
        chk_nonnumeric_addrdr->down_box(FL_DOWN_BOX);
        chk_nonnumeric_addrdr->labelsize(12);
        chk_nonnumeric_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(nonnumeric_addrdr));
      } // Fl_Check_Button* chk_nonnumeric_addrdr
      { chk_automaticallycheckid_addrdr = new Fl_Check_Button(305, 120, 170, 30, "Automatically check ID");
        chk_automaticallycheckid_addrdr->down_box(FL_DOWN_BOX);
        chk_automaticallycheckid_addrdr->labelsize(13);
        chk_automaticallycheckid_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(automaticallycheckid_addrdr));
      } // Fl_Check_Button* chk_automaticallycheckid_addrdr
      { checkid_addrdr = new Fl_Button(460, 120, 80, 30, "Check ID");
        checkid_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(checkid_addrdr));
      } // Fl_Button* checkid_addrdr
      { btn_addreader_addrdr = new Fl_Button(250, 165, 290, 40, "ADD READER");
        btn_addreader_addrdr->labelsize(31);
        btn_addreader_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(addreader_addrdr));
      } // Fl_Button* btn_addreader_addrdr
      { btn_undolastadd_addrdr = new Fl_Button(0, 165, 245, 40, "Undo last add");
        btn_undolastadd_addrdr->labelsize(25);
        btn_undolastadd_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(undolastadd_addrdr));
      } // Fl_Button* btn_undolastadd_addrdr
      { Fl_Text_Display* o = new Fl_Text_Display(210, 205, 10, 30, "Search");
        o->labelsize(32);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { cic_searchby_addrdr = new Fl_Choice(330, 255, 105, 25, "Search by:");
        cic_searchby_addrdr->down_box(FL_BORDER_BOX);
        cic_searchby_addrdr->labelsize(17);
        cic_searchby_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(searchby_addrdr));
        cic_searchby_addrdr->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_addrdr
      { btn_search_addrdr = new Fl_Button(435, 235, 105, 45, "SEARCH");
        btn_search_addrdr->labelsize(21);
        btn_search_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(search_addrdr));
      } // Fl_Button* btn_search_addrdr
      { // Search results, click to fill text fields
        brw_search_addrdr = new Fl_Browser(5, 280, 535, 90);
        brw_search_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(browser_addrdr));
      } // Fl_Browser* brw_search_addrdr
      { inp_search_addrdr = new Fl_Input(90, 240, 240, 40, "Search term:");
      } // Fl_Input* inp_search_addrdr
      { btn_help_addrdr = new Fl_Button(5, 25, 75, 35, "HELP");
        btn_help_addrdr->labelsize(21);
        btn_help_addrdr->callback((Fl_Callback*)BTN_CB, (void*)(HELP_addrdr));
      } // Fl_Button* btn_help_addrdr
      group_addreaders->end();
    } // Fl_Group* group_addreaders
    { // Add loans
      group_addloans = new Fl_Group(0, 25, 540, 350);
      group_addloans->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(170, 25, 10, 30, "Add Loans");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_bookid_addlns = new Fl_Input(55, 60, 65, 30, "Book ID");
      } // Fl_Input* inp_bookid_addlns
      { cic_searchby_addlns = new Fl_Choice(430, 175, 105, 25, "Search by:");
        cic_searchby_addlns->down_box(FL_BORDER_BOX);
        cic_searchby_addlns->labelsize(17);
        cic_searchby_addlns->callback((Fl_Callback*)BTN_CB, (void*)(searchby_addlns));
        cic_searchby_addlns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_addlns
      { btn_search_addlns = new Fl_Button(10, 200, 525, 30, "SEARCH");
        btn_search_addlns->labelsize(21);
        btn_search_addlns->callback((Fl_Callback*)BTN_CB, (void*)(search_addlns));
      } // Fl_Button* btn_search_addlns
      { // Search results, click to fill text fields
        brw_search_addlns = new Fl_Browser(5, 230, 535, 140);
        brw_search_addlns->callback((Fl_Callback*)BTN_CB, (void*)(browser_addlns));
      } // Fl_Browser* brw_search_addlns
      { inp_search_addlns = new Fl_Input(85, 160, 235, 40, "Search term:");
      } // Fl_Input* inp_search_addlns
      { cic_searchwhat_addlns = new Fl_Choice(320, 175, 105, 25, "Search what:");
        cic_searchwhat_addlns->down_box(FL_BORDER_BOX);
        cic_searchwhat_addlns->labelsize(17);
        cic_searchwhat_addlns->callback((Fl_Callback*)BTN_CB, (void*)(searchwhat_addlns));
        cic_searchwhat_addlns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchwhat_addlns
      { inp_readerid_addlns = new Fl_Input(190, 60, 65, 30, "Reader ID");
      } // Fl_Input* inp_readerid_addlns
      { inp_loanid_addlns = new Fl_Input(310, 60, 65, 30, "Loan ID");
      } // Fl_Input* inp_loanid_addlns
      { inp_expirydate_addlns = new Fl_Input(175, 90, 85, 30, "Expiry date (yyyy-mm-dd): ");
      } // Fl_Input* inp_expirydate_addlns
      { chk_generate_addlns = new Fl_Check_Button(375, 60, 25, 25, "Generate ID");
        chk_generate_addlns->down_box(FL_DOWN_BOX);
        chk_generate_addlns->labelsize(17);
        chk_generate_addlns->callback((Fl_Callback*)BTN_CB, (void*)(generate_addlns));
      } // Fl_Check_Button* chk_generate_addlns
      { Fl_Text_Display* o = new Fl_Text_Display(355, 90, 185, 25, "Current date:");
        o->align(Fl_Align(FL_ALIGN_LEFT));
      } // Fl_Text_Display* o
      { btn_addloan_addlns = new Fl_Button(225, 120, 310, 30, "ADD LOAN");
        btn_addloan_addlns->labelsize(21);
        btn_addloan_addlns->callback((Fl_Callback*)BTN_CB, (void*)(ADDLOAN));
      } // Fl_Button* btn_addloan_addlns
      { btn_undolastadd_addlns = new Fl_Button(0, 120, 220, 30, "Undo last loan");
        btn_undolastadd_addlns->labelsize(21);
        btn_undolastadd_addlns->callback((Fl_Callback*)BTN_CB, (void*)(undolastadd_addlns));
      } // Fl_Button* btn_undolastadd_addlns
      { btn_help_addlns = new Fl_Button(5, 25, 75, 35, "HELP");
        btn_help_addlns->labelsize(21);
        btn_help_addlns->callback((Fl_Callback*)BTN_CB, (void*)(HELP_addlns));
      } // Fl_Button* btn_help_addlns
      group_addloans->end();
    } // Fl_Group* group_addloans
    { // edit books
      group_editbooks = new Fl_Group(0, 25, 540, 335);
      group_editbooks->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(205, 210, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_searchterm_editbk = new Fl_Input(95, 240, 235, 30, "Search term:");
        inp_searchterm_editbk->labelsize(16);
      } // Fl_Input* inp_searchterm_editbk
      { cic_searchby_editbk = new Fl_Choice(330, 240, 105, 25, "Search by:");
        cic_searchby_editbk->down_box(FL_BORDER_BOX);
        cic_searchby_editbk->labelsize(17);
        cic_searchby_editbk->callback((Fl_Callback*)BTN_CB, (void*)(searchby_editbk));
        cic_searchby_editbk->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_editbk
      { btn_search_editbk = new Fl_Button(435, 220, 105, 45, "SEARCH");
        btn_search_editbk->labelsize(21);
        btn_search_editbk->callback((Fl_Callback*)BTN_CB, (void*)(search_editbk));
      } // Fl_Button* btn_search_editbk
      { // Search results, click to fill text fields
        brw_search_editbk = new Fl_Browser(5, 265, 535, 90);
        brw_search_editbk->callback((Fl_Callback*)BTN_CB, (void*)(browser_editbk));
      } // Fl_Browser* brw_search_editbk
      { btn_help_editbk = new Fl_Button(0, 25, 70, 30, "HELP");
        btn_help_editbk->labelsize(21);
        btn_help_editbk->callback((Fl_Callback*)BTN_CB, (void*)(HELP_editbk));
      } // Fl_Button* btn_help_editbk
      { Fl_Text_Display* o = new Fl_Text_Display(165, 25, 10, 30, "Edit Books");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_title_editbk = new Fl_Input(45, 60, 410, 30, "Title");
        inp_title_editbk->labelsize(21);
      } // Fl_Input* inp_title_editbk
      { btn_checktitle_editbk = new Fl_Button(460, 60, 80, 30, "Check Title");
        btn_checktitle_editbk->callback((Fl_Callback*)BTN_CB, (void*)(checktitle_editbk));
      } // Fl_Button* btn_checktitle_editbk
      { inp_author_editbk = new Fl_Input(65, 90, 390, 30, "Author");
        inp_author_editbk->labelsize(21);
      } // Fl_Input* inp_author_editbk
      { inp_bookid_editbk = new Fl_Input(80, 120, 160, 30, "Book ID");
        inp_bookid_editbk->labelsize(21);
      } // Fl_Input* inp_bookid_editbk
      { btn_checkauthor_editbk = new Fl_Button(460, 90, 80, 30, "Check Author");
        btn_checkauthor_editbk->labelsize(12);
        btn_checkauthor_editbk->callback((Fl_Callback*)BTN_CB, (void*)(checkauthor_editbk));
      } // Fl_Button* btn_checkauthor_editbk
      { btn_checktitle_editbk = new Fl_Button(460, 120, 80, 30, "Check Title");
        btn_checktitle_editbk->callback((Fl_Callback*)BTN_CB, (void*)(checktitle_editbk));
      } // Fl_Button* btn_checktitle_editbk
      { chk_nonnumeric_editbk = new Fl_Check_Button(365, 120, 90, 30, "Non-numeric");
        chk_nonnumeric_editbk->down_box(FL_DOWN_BOX);
        chk_nonnumeric_editbk->labelsize(12);
        chk_nonnumeric_editbk->callback((Fl_Callback*)BTN_CB, (void*)(nonnumeric_editbk));
      } // Fl_Check_Button* chk_nonnumeric_editbk
      { chk_automaticallycheck_editbk = new Fl_Check_Button(240, 120, 125, 30, "Automatically check");
        chk_automaticallycheck_editbk->down_box(FL_DOWN_BOX);
        chk_automaticallycheck_editbk->labelsize(12);
        chk_automaticallycheck_editbk->callback((Fl_Callback*)BTN_CB, (void*)(automaticallycheck_editbk));
      } // Fl_Check_Button* chk_automaticallycheck_editbk
      { cic_category_editbk = new Fl_Choice(65, 150, 200, 25, "Category");
        cic_category_editbk->down_box(FL_BORDER_BOX);
        cic_category_editbk->callback((Fl_Callback*)BTN_CB, (void*)(category_editbk));
      } // Fl_Choice* cic_category_editbk
      { cic_status_editbk = new Fl_Choice(315, 150, 225, 25, "Status");
        cic_status_editbk->down_box(FL_BORDER_BOX);
        cic_status_editbk->callback((Fl_Callback*)BTN_CB, (void*)(status_editbk));
      } // Fl_Choice* cic_status_editbk
      { btn_editbook_editbk = new Fl_Button(225, 175, 315, 40, "EDIT BOOK");
        btn_editbook_editbk->labelsize(21);
        btn_editbook_editbk->callback((Fl_Callback*)BTN_CB, (void*)(EDITBOOK));
      } // Fl_Button* btn_editbook_editbk
      { btn_undolastedit_editbk = new Fl_Button(5, 175, 210, 40, "Undo last edit");
        btn_undolastedit_editbk->labelsize(21);
        btn_undolastedit_editbk->callback((Fl_Callback*)BTN_CB, (void*)(undolastedit_editbk));
      } // Fl_Button* btn_undolastedit_editbk
      group_editbooks->end();
    } // Fl_Group* group_editbooks
    { // delete books
      group_deletebooks = new Fl_Group(0, 25, 540, 335);
      group_deletebooks->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(205, 60, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_search_delbks = new Fl_Input(95, 90, 235, 30, "Search term:");
        inp_search_delbks->labelsize(16);
      } // Fl_Input* inp_search_delbks
      { cic_searchby_delbks = new Fl_Choice(330, 95, 105, 25, "Search by:");
        cic_searchby_delbks->down_box(FL_BORDER_BOX);
        cic_searchby_delbks->labelsize(17);
        cic_searchby_delbks->callback((Fl_Callback*)BTN_CB, (void*)(searchby_delbks));
        cic_searchby_delbks->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_delbks
      { btn_search_delbks = new Fl_Button(435, 75, 105, 45, "SEARCH");
        btn_search_delbks->labelsize(21);
        btn_search_delbks->callback((Fl_Callback*)BTN_CB, (void*)(search_delbks));
      } // Fl_Button* btn_search_delbks
      { // Search results, click to fill text fields
        brw_search_delbks = new Fl_Browser(5, 125, 535, 90);
        brw_search_delbks->callback((Fl_Callback*)BTN_CB, (void*)(browser_delbks));
      } // Fl_Browser* brw_search_delbks
      { btn_help_delbks = new Fl_Button(0, 25, 70, 30, "HELP");
        btn_help_delbks->labelsize(21);
        btn_help_delbks->callback((Fl_Callback*)BTN_CB, (void*)(HELP_delbks));
      } // Fl_Button* btn_help_delbks
      { Fl_Text_Display* o = new Fl_Text_Display(155, 25, 10, 30, "Delete Books");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_bookid_delbks = new Fl_Input(475, 250, 65, 25, "Book ID:");
        inp_bookid_delbks->labelsize(16);
        inp_bookid_delbks->callback((Fl_Callback*)BTN_CB, (void*)(bookid_delbks));
      } // Fl_Input* inp_bookid_delbks
      { btn_deletebook_delbks = new Fl_Button(330, 215, 210, 35, "DELETE BOOK");
        btn_deletebook_delbks->labelsize(21);
        btn_deletebook_delbks->callback((Fl_Callback*)BTN_CB, (void*)(DELTEBOOK));
      } // Fl_Button* btn_deletebook_delbks
      { btn_undolastdelete_delbks = new Fl_Button(190, 215, 140, 35, "Undo last delete");
        btn_undolastdelete_delbks->labelsize(16);
        btn_undolastdelete_delbks->callback((Fl_Callback*)BTN_CB, (void*)(undolastdelete_delbks));
      } // Fl_Button* btn_undolastdelete_delbks
      { Fl_Text_Display* o = new Fl_Text_Display(135, 250, 10, 30, "Search deleted books");
        o->labelsize(17);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { // Search results, click to fill text fields
        brw_searchdeleted_delbks = new Fl_Browser(5, 275, 535, 85);
        brw_searchdeleted_delbks->callback((Fl_Callback*)BTN_CB, (void*)(browserdeleted_delbks));
      } // Fl_Browser* brw_searchdeleted_delbks
      { btn_restoreselected_delbks = new Fl_Button(5, 250, 130, 25, "Restore selected");
        btn_restoreselected_delbks->labelsize(16);
        btn_restoreselected_delbks->callback((Fl_Callback*)BTN_CB, (void*)(restoreselected_delbks));
      } // Fl_Button* btn_restoreselected_delbks
      { btn_searchdeleted_delbks = new Fl_Button(325, 250, 80, 25, "Search");
        btn_searchdeleted_delbks->labelsize(17);
        btn_searchdeleted_delbks->callback((Fl_Callback*)BTN_CB, (void*)(searchdeleted_delbks));
      } // Fl_Button* btn_searchdeleted_delbks
      group_deletebooks->end();
    } // Fl_Group* group_deletebooks
    { // Edit readers
      group_editreaders = new Fl_Group(0, 25, 540, 345);
      group_editreaders->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(150, 25, 10, 30, "Edit Readers");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_readername_editrdr = new Fl_Input(60, 60, 380, 30, "Name");
        inp_readername_editrdr->labelsize(21);
      } // Fl_Input* inp_readername_editrdr
      { btn_checkname_editrdr = new Fl_Button(440, 60, 100, 30, "Check Name");
        btn_checkname_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(checkname_editrdr));
      } // Fl_Button* btn_checkname_editrdr
      { inp_readersurname_editrdr = new Fl_Input(70, 90, 370, 30, "Surname");
        inp_readersurname_editrdr->labelsize(16);
      } // Fl_Input* inp_readersurname_editrdr
      { inp_grade_editrdr = new Fl_Input(45, 120, 20, 30, "Grade");
        inp_grade_editrdr->labelsize(15);
      } // Fl_Input* inp_grade_editrdr
      { btn_checksurname_editrdr = new Fl_Button(440, 90, 100, 30, "Check Surname");
        btn_checksurname_editrdr->labelsize(12);
        btn_checksurname_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(checksurname_editrdr));
      } // Fl_Button* btn_checksurname_editrdr
      { inp_class_editrdr = new Fl_Input(110, 120, 20, 30, "Class");
        inp_class_editrdr->labelsize(15);
      } // Fl_Input* inp_class_editrdr
      { inp_readerid_editrdr = new Fl_Input(200, 120, 105, 30, "Reader ID");
        inp_readerid_editrdr->labelsize(15);
      } // Fl_Input* inp_readerid_editrdr
      { chk_nonnumeric_editrd = new Fl_Check_Button(305, 140, 90, 30, "Non-numeric");
        chk_nonnumeric_editrd->down_box(FL_DOWN_BOX);
        chk_nonnumeric_editrd->labelsize(12);
        chk_nonnumeric_editrd->callback((Fl_Callback*)BTN_CB, (void*)(nonnumeric_editrdr));
      } // Fl_Check_Button* chk_nonnumeric_editrd
      { chk_automaticallycheckid_editrdr = new Fl_Check_Button(305, 120, 170, 30, "Automatically check ID");
        chk_automaticallycheckid_editrdr->down_box(FL_DOWN_BOX);
        chk_automaticallycheckid_editrdr->labelsize(13);
        chk_automaticallycheckid_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(automaticallycheckid-editrdr));
      } // Fl_Check_Button* chk_automaticallycheckid_editrdr
      { btn_checkid_editrdr = new Fl_Button(460, 120, 80, 30, "Check ID");
        btn_checkid_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(checkid_editrdr));
      } // Fl_Button* btn_checkid_editrdr
      { btn_editreader_editrdr = new Fl_Button(250, 165, 290, 40, "EDIT READER");
        btn_editreader_editrdr->labelsize(31);
        btn_editreader_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(EDITREADER));
      } // Fl_Button* btn_editreader_editrdr
      { btn_undolastadd_editrdr = new Fl_Button(0, 165, 245, 40, "Undo last add");
        btn_undolastadd_editrdr->labelsize(25);
        btn_undolastadd_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(undolastadd_editrdr));
      } // Fl_Button* btn_undolastadd_editrdr
      { Fl_Text_Display* o = new Fl_Text_Display(210, 205, 10, 30, "Search");
        o->labelsize(32);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { cic_searchby_editrdr = new Fl_Choice(330, 255, 105, 25, "Search by:");
        cic_searchby_editrdr->down_box(FL_BORDER_BOX);
        cic_searchby_editrdr->labelsize(17);
        cic_searchby_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(searchby_editrdr));
        cic_searchby_editrdr->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_editrdr
      { btn_search_editrdr = new Fl_Button(435, 235, 105, 45, "SEARCH");
        btn_search_editrdr->labelsize(21);
        btn_search_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(search_editrdr));
      } // Fl_Button* btn_search_editrdr
      { // Search results, click to fill text fields
        brw_search_editrdr = new Fl_Browser(5, 280, 535, 90);
        brw_search_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(browser_editrdr));
      } // Fl_Browser* brw_search_editrdr
      { inp_search_editrdr = new Fl_Input(90, 240, 240, 40, "Search term:");
      } // Fl_Input* inp_search_editrdr
      { btn_help_editrdr = new Fl_Button(5, 25, 75, 35, "HELP");
        btn_help_editrdr->labelsize(21);
        btn_help_editrdr->callback((Fl_Callback*)BTN_CB, (void*)(HELP_editrdr));
      } // Fl_Button* btn_help_editrdr
      group_editreaders->end();
    } // Fl_Group* group_editreaders
    { // Delete readers
      group_deletereaders = new Fl_Group(0, 25, 540, 340);
      group_deletereaders->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(205, 60, 10, 30, "Search");
        o->labelsize(31);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_search_delrdr = new Fl_Input(95, 90, 235, 30, "Search term:");
        inp_search_delrdr->labelsize(16);
      } // Fl_Input* inp_search_delrdr
      { cic_searchby_delrdr = new Fl_Choice(330, 95, 105, 25, "Search by:");
        cic_searchby_delrdr->down_box(FL_BORDER_BOX);
        cic_searchby_delrdr->labelsize(17);
        cic_searchby_delrdr->callback((Fl_Callback*)BTN_CB, (void*)(searchby_delrdr));
        cic_searchby_delrdr->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_delrdr
      { btn_search_delrdr = new Fl_Button(435, 75, 105, 45, "SEARCH");
        btn_search_delrdr->labelsize(21);
        btn_search_delrdr->callback((Fl_Callback*)BTN_CB, (void*)(search_delrdr));
      } // Fl_Button* btn_search_delrdr
      { // Search results, click to fill text fields
        brw_search_delrdr = new Fl_Browser(5, 125, 535, 90);
        brw_search_delrdr->callback((Fl_Callback*)BTN_CB, (void*)(browser_delrdr));
      } // Fl_Browser* brw_search_delrdr
      { btn_help-delrdr = new Fl_Button(0, 25, 70, 30, "HELP");
        btn_help-delrdr->labelsize(21);
        btn_help-delrdr->callback((Fl_Callback*)BTN_CB, (void*)(HELP_delrdr));
      } // Fl_Button* btn_help-delrdr
      { Fl_Text_Display* o = new Fl_Text_Display(130, 25, 10, 30, "Delete Readers");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_readerid_delrdr = new Fl_Input(70, 215, 120, 35, "Reader ID:");
        inp_readerid_delrdr->labelsize(16);
      } // Fl_Input* inp_readerid_delrdr
      { btn_deletereader_delrdr = new Fl_Button(330, 215, 210, 35, "DELETE READER");
        btn_deletereader_delrdr->labelsize(21);
        btn_deletereader_delrdr->callback((Fl_Callback*)BTN_CB, (void*)(DELETEREADER));
      } // Fl_Button* btn_deletereader_delrdr
      { btn_undolastdelete_delrdr = new Fl_Button(190, 215, 140, 35, "Undo last delete");
        btn_undolastdelete_delrdr->labelsize(16);
        btn_undolastdelete_delrdr->callback((Fl_Callback*)BTN_CB, (void*)(undolastdelete_delrdr));
      } // Fl_Button* btn_undolastdelete_delrdr
      { Fl_Text_Display* o = new Fl_Text_Display(175, 250, 10, 30, "Search deleted readers");
        o->labelsize(21);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { // Search results, click to fill text fields
        brw_deleted_delrdr = new Fl_Browser(5, 275, 535, 85);
        brw_deleted_delrdr->callback((Fl_Callback*)BTN_CB, (void*)(browser_deleted));
      } // Fl_Browser* brw_deleted_delrdr
      { btn_restoreselected_delrdr = new Fl_Button(5, 250, 170, 25, "Restore selected");
        btn_restoreselected_delrdr->labelsize(16);
        btn_restoreselected_delrdr->callback((Fl_Callback*)BTN_CB, (void*)(restoredeleted_delrdr));
      } // Fl_Button* btn_restoreselected_delrdr
      group_deletereaders->end();
    } // Fl_Group* group_deletereaders
    { // Edit loans
      group_editloans = new Fl_Group(0, 25, 540, 345);
      group_editloans->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(170, 25, 10, 30, "Edit Loans");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { inp_bookid_editlns = new Fl_Input(55, 60, 65, 30, "Book ID");
      } // Fl_Input* inp_bookid_editlns
      { cic_searchby_editlns = new Fl_Choice(430, 175, 105, 25, "Search by:");
        cic_searchby_editlns->down_box(FL_BORDER_BOX);
        cic_searchby_editlns->labelsize(17);
        cic_searchby_editlns->callback((Fl_Callback*)BTN_CB, (void*)(searchby_editlns));
        cic_searchby_editlns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_editlns
      { btn_search_editlns = new Fl_Button(10, 200, 525, 30, "SEARCH");
        btn_search_editlns->labelsize(21);
        btn_search_editlns->callback((Fl_Callback*)BTN_CB, (void*)(search_editlns));
      } // Fl_Button* btn_search_editlns
      { // Search results, click to fill text fields
        brw_search_editlns = new Fl_Browser(5, 230, 535, 140);
        brw_search_editlns->callback((Fl_Callback*)BTN_CB, (void*)(browser_editlns));
      } // Fl_Browser* brw_search_editlns
      { inp_search_editlns = new Fl_Input(85, 160, 235, 40, "Search term:");
      } // Fl_Input* inp_search_editlns
      { cic_searchwhat_editlns = new Fl_Choice(320, 175, 105, 25, "Search:");
        cic_searchwhat_editlns->down_box(FL_BORDER_BOX);
        cic_searchwhat_editlns->labelsize(17);
        cic_searchwhat_editlns->callback((Fl_Callback*)BTN_CB, (void*)(searchwhat_editlns));
        cic_searchwhat_editlns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchwhat_editlns
      { inp_readerid_editlns = new Fl_Input(190, 60, 65, 30, "Reader ID");
      } // Fl_Input* inp_readerid_editlns
      { inp_loanid_editlns = new Fl_Input(310, 60, 65, 30, "Loan ID");
      } // Fl_Input* inp_loanid_editlns
      { chk_autogenerate_editlns = new Fl_Check_Button(375, 60, 110, 30, "auto-generate");
        chk_autogenerate_editlns->down_box(FL_DOWN_BOX);
        chk_autogenerate_editlns->callback((Fl_Callback*)BTN_CB, (void*)(autogenerate_editlns));
      } // Fl_Check_Button* chk_autogenerate_editlns
      { inp_expirydate_editlns = new Fl_Input(175, 90, 85, 30, "Expiry date (yyyy-mm-dd): ");
      } // Fl_Input* inp_expirydate_editlns
      { Fl_Text_Display* o = new Fl_Text_Display(345, 90, 185, 25, "Current date:");
        o->align(Fl_Align(FL_ALIGN_LEFT));
      } // Fl_Text_Display* o
      { btn_editloans_editlns = new Fl_Button(225, 120, 310, 30, "EDIT LOAN");
        btn_editloans_editlns->labelsize(21);
        btn_editloans_editlns->callback((Fl_Callback*)BTN_CB, (void*)(EDITLOAN));
      } // Fl_Button* btn_editloans_editlns
      { btn_undolastedit_editlns = new Fl_Button(0, 120, 220, 30, "Undo last loan edit");
        btn_undolastedit_editlns->labelsize(21);
        btn_undolastedit_editlns->callback((Fl_Callback*)BTN_CB, (void*)(undolastedit_editlns));
      } // Fl_Button* btn_undolastedit_editlns
      { btn_help_editlns = new Fl_Button(5, 25, 75, 35, "HELP");
        btn_help_editlns->labelsize(21);
        btn_help_editlns->callback((Fl_Callback*)BTN_CB, (void*)(HELP_editlns));
      } // Fl_Button* btn_help_editlns
      group_editloans->end();
    } // Fl_Group* group_editloans
    { // mark loans 
      group_markloans = new Fl_Group(0, 25, 545, 350);
      group_markloans->hide();
      { Fl_Text_Display* o = new Fl_Text_Display(170, 25, 10, 30, "Mark Loans");
        o->labelsize(41);
        o->align(Fl_Align(520));
      } // Fl_Text_Display* o
      { cic_searchby_marklns = new Fl_Choice(430, 75, 105, 25, "Search by:");
        cic_searchby_marklns->down_box(FL_BORDER_BOX);
        cic_searchby_marklns->labelsize(17);
        cic_searchby_marklns->callback((Fl_Callback*)BTN_CB, (void*)(searchby_marklns));
        cic_searchby_marklns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchby_marklns
      { btn_search_marklns = new Fl_Button(10, 100, 525, 30, "SEARCH");
        btn_search_marklns->labelsize(21);
        btn_search_marklns->callback((Fl_Callback*)BTN_CB, (void*)(search_marklns));
      } // Fl_Button* btn_search_marklns
      { // Search results, click to fill text fields
        brw_select_marklns = new Fl_Browser(5, 130, 535, 140);
        brw_select_marklns->callback((Fl_Callback*)BTN_CB, (void*)(browser_marklns));
      } // Fl_Browser* brw_select_marklns
      { inp_search_marklns = new Fl_Input(90, 60, 235, 40, "Search term:");
      } // Fl_Input* inp_search_marklns
      { cic_searchwhat_marklns = new Fl_Choice(325, 75, 105, 25, "Search:");
        cic_searchwhat_marklns->down_box(FL_BORDER_BOX);
        cic_searchwhat_marklns->labelsize(17);
        cic_searchwhat_marklns->callback((Fl_Callback*)BTN_CB, (void*)(searchwhat_marklns));
        cic_searchwhat_marklns->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Choice* cic_searchwhat_marklns
      { btn_help_marklns = new Fl_Button(5, 25, 75, 35, "HELP");
        btn_help_marklns->labelsize(21);
        btn_help_marklns->callback((Fl_Callback*)BTN_CB, (void*)(HELP_marklns));
      } // Fl_Button* btn_help_marklns
      { inp_prolongby_marklns = new Fl_Input(140, 275, 100, 30, "Prolong by (days)");
        inp_prolongby_marklns->labelsize(17);
      } // Fl_Input* inp_prolongby_marklns
      { btn_prolong_marklns = new Fl_Button(240, 275, 140, 30, "Prolong");
        btn_prolong_marklns->labelsize(18);
        btn_prolong_marklns->callback((Fl_Callback*)BTN_CB, (void*)(prolong_marklns));
      } // Fl_Button* btn_prolong_marklns
      { btn_markreturned_marklns = new Fl_Button(385, 275, 150, 30, "Mark as returned");
        btn_markreturned_marklns->labelsize(18);
        btn_markreturned_marklns->callback((Fl_Callback*)BTN_CB, (void*)(markreturned_marklns));
      } // Fl_Button* btn_markreturned_marklns
      { btn_marklost_marklns = new Fl_Button(385, 310, 150, 30, "Mark as lost");
        btn_marklost_marklns->labelsize(18);
        btn_marklost_marklns->callback((Fl_Callback*)BTN_CB, (void*)(marklost_marklns));
      } // Fl_Button* btn_marklost_marklns
      group_markloans->end();
    } // Fl_Group* group_markloans
    { // backdrop
      group_backdrop = new Fl_Group(0, 25, 540, 360);
      group_backdrop->hide();
      { clk_time_backdrop = new Fl_Clock(175, 30, 210, 175, "System time");
        clk_time_backdrop->labelsize(41);
      } // Fl_Clock* clk_time_backdrop
      { Fl_Text_Display* o = new Fl_Text_Display(5, 260, 5, 25, "https://github.com/C0m3b4ck/ShelfSight");
        o->labelsize(27);
        o->align(Fl_Align(296));
      } // Fl_Text_Display* o
      { Fl_Text_Display* o = new Fl_Text_Display(15, 305, 10, 35, "PrinterFixer on YouTube.com");
        o->labelsize(35);
        o->align(Fl_Align(296));
      } // Fl_Text_Display* o
      group_backdrop->end();
    } // Fl_Group* group_backdrop
    { group_selectdb = new Fl_Group(0, 25, 540, 330);
      { Fl_Text_Display* o = new Fl_Text_Display(95, 25, 10, 35, "Select Databases");
        o->labelsize(44);
        o->align(Fl_Align(296));
      } // Fl_Text_Display* o
      { flbrw_bookdb_selectdb = new Fl_File_Browser(5, 85, 165, 145, "Select book DB:");
        flbrw_bookdb_selectdb->labelsize(21);
        flbrw_bookdb_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(bookdb_selectdb));
        flbrw_bookdb_selectdb->align(Fl_Align(33));
      } // Fl_File_Browser* flbrw_bookdb_selectdb
      { flbrw_readerdb_selectdb = new Fl_File_Browser(190, 85, 165, 145, "Select reader DB:");
        flbrw_readerdb_selectdb->labelsize(21);
        flbrw_readerdb_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(readerdb_selectdb));
        flbrw_readerdb_selectdb->align(Fl_Align(33));
      } // Fl_File_Browser* flbrw_readerdb_selectdb
      { flbrw_loandb_selectdb = new Fl_File_Browser(370, 85, 165, 145, "Select loan DB:");
        flbrw_loandb_selectdb->labelsize(21);
        flbrw_loandb_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(loandb_selectdb));
        flbrw_loandb_selectdb->align(Fl_Align(33));
      } // Fl_File_Browser* flbrw_loandb_selectdb
      { mnubtn_saveconfig_selectdb = new Fl_Menu_Button(190, 235, 165, 45, "Save config");
        mnubtn_saveconfig_selectdb->labelsize(25);
        mnubtn_saveconfig_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(saveconfig_selectdb));
        mnubtn_saveconfig_selectdb->menu(menu_mnubtn_saveconfig_selectdb);
      } // Fl_Menu_Button* mnubtn_saveconfig_selectdb
      { mnubtn_loadconfig_selectdb = new Fl_Menu_Button(5, 235, 165, 45, "Load config");
        mnubtn_loadconfig_selectdb->labelsize(25);
        mnubtn_loadconfig_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(loadconfig_selectdb));
        mnubtn_loadconfig_selectdb->menu(menu_mnubtn_loadconfig_selectdb);
      } // Fl_Menu_Button* mnubtn_loadconfig_selectdb
      { btn_back_selectdb = new Fl_Button(10, 285, 260, 65, "Back");
        btn_back_selectdb->labelsize(48);
        btn_back_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(BACK_selectdb));
      } // Fl_Button* btn_back_selectdb
      { btn_setselected_selectdb = new Fl_Button(275, 285, 260, 65, "Set selected");
        btn_setselected_selectdb->labelsize(43);
        btn_setselected_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(setselected_selectdb));
      } // Fl_Button* btn_setselected_selectdb
      { mnubtn_verifydb_selectdb = new Fl_Menu_Button(370, 235, 165, 45, "Verify DB");
        mnubtn_verifydb_selectdb->labelsize(25);
        mnubtn_verifydb_selectdb->callback((Fl_Callback*)BTN_CB, (void*)(verifydb_selectdb));
        mnubtn_verifydb_selectdb->menu(menu_mnubtn_verifydb_selectdb);
      } // Fl_Menu_Button* mnubtn_verifydb_selectdb
      group_selectdb->end();
    } // Fl_Group* group_selectdb
    o->end();
  } // Fl_Double_Window* o
  return window_assistant;
}

/**
 For non-menu buttons (the ones in groups)
*/
void BTN_CB(Fl_Widget* w, void* data) {
  // Assume you have a global or accessible AppUI pointer named app_ui
  // and it contains: Fl_Input* inp_usr_log; Fl_Input* inp_pwd_log; (etc.)
  
  struct AppUI
  {
                  Fl_Input* inp_usr-reg;
                  Fl_Input* inp_pwd1-reg;
                  Fl_Input* inp_pwd2-reg;
                  Fl_Input* inp_title-addbk;
                  Fl_Input* inp_id-addbk;
                  Fl_Input* inp_author-addbk;
                  Fl_Input* inp_name-addrdr;
                  Fl_Input* inp_surname-addrdr;
                  Fl_Input* inp_grade-addrdr;
                  Fl_Input* inp_class-addrdr;
                  Fl_Input* inp_readerid-addrdr;
                  Fl_Input* inp_search-addrdr;
                  Fl_Input* inp_bookid-addlns;
                  Fl_Input* inp_search-addlns;
                  Fl_Input* inp_readerid-addlns;
                  Fl_Input* inp_loanid-addlns;
                  Fl_Input* inp_expirydate-addlns;
                  Fl_Input* inp_searchterm-editbk;
                  Fl_Input* inp_title-editbk;
                  Fl_Input* inp_author-editbk;
                  Fl_Input* inp_bookid-editbk;
                  Fl_Input* inp_search-delbks;
                  Fl_Input* inp_bookid-delbks;
                  Fl_Input* inp_readername-editrdr;
                  Fl_Input* inp_readersurname-editrdr;
                  Fl_Input* inp_grade-editrdr;
                  Fl_Input* inp_class-editrdr;
                  Fl_Input* inp_readerid-editrdr;
                  Fl_Input* inp_search-editrdr;
                  Fl_Input* inp_search-delrdr;
                  Fl_Input* inp_readerid-delrdr;
                  Fl_Input* inp_bookid-editlns;
                  Fl_Input* inp_search-editlns;
                  Fl_Input* inp_readerid-editlns;
                  Fl_Input* inp_loanid-editlns;
                  Fl_Input* inp_expirydate-editlns;
                  Fl_Input* inp_search-marklns;
                  Fl_Input* inp_prolongby-marklns;
                  // add input fields from any DB menus
  }
  
  void BTN_CB(Fl_Widget* w, void* data) {
    std::string function_data = *(std::string*)data;
  
    std::cout << "BTN_CB called with " << function_data << " as data. \n";
  
    if (function_data == "login_btn")
    {
      // ADDED: read login inputs from your AppUI
      std::string usr = (app_ui->inp_usr_log ? app_ui->inp_usr_log->value() : "");
      std::string pwd = (app_ui->inp_pwd_log ? app_ui->inp_pwd_log->value() : "");
  
      std::cout << "Login button clicked!\n";
      std::cout << "usr=" << usr << "\n";
      std::cout << "pwd=" << pwd << "\n";
  
      // Pass usr/pwd to your function here
      // login_function(usr, pwd);
    } 
    else 
    {
      std::cerr << "Unknown function data: " << function_data << " - this is a programmer error! \n";
    }
  }
}

/**
 Hides all groups
*/
void hide_all_groups() {
  group_register.hide();
  group_login().hide;
  group_addbooks().hide;
  group_addreaders().hide;
  group_addloans().hide;
}
