#pragma once

enum GuiView
{
    VIEW_LOGIN,
    VIEW_REGISTER,
    VIEW_ADD_BOOKS,
    VIEW_EDIT_BOOKS,
    VIEW_DELETE_BOOKS,
    VIEW_MANAGE_CATEGORIES,
    VIEW_ADD_READERS,
    VIEW_EDIT_READERS,
    VIEW_DELETE_READERS,
    VIEW_IMPORT_READERS,
    VIEW_ADD_LOANS,
    VIEW_RETURN_LOANS,
    VIEW_LIST_LOANS,
    VIEW_EDIT_LOANS,
    VIEW_REMOVE_LOANS,
    VIEW_MARK_LOST,
    VIEW_PROLONG,
    VIEW_EXPIRED,
    VIEW_SEARCH_LOANS,
    VIEW_SELECT_DB,
    VIEW_SETTINGS_ACCOUNT,
    VIEW_SETTINGS_THEME,
    VIEW_SETTINGS_PERF,
    VIEW_SETTINGS_NET,
    VIEW_SETTINGS_OTHER,
    VIEW_RESET_SETTINGS,
    VIEW_ABOUT,
};

void gui_imgui_run();
