SOURCES += sqlite3/sqlite3.c

INCLUDEPATH += sqlite3

DEFINES += \
    SQLITE_ENABLE_COLUMN_METADATA \
    SQLITE_ENABLE_RTREE \
    SQLITE_ENABLE_DBSTAT_VTAB \
    SQLITE_THREADSAFE=1 \
    SQLITE_USE_URI=1 \
    SQLITE_DEFAULT_MEMSTATUS=0 \
    SQLITE_DEFAULT_WAL_SYNCHRONOUS=1 \
    SQLITE_LIKE_DOESNT_MATCH_BLOBS=1 \
    SQLITE_MAX_EXPR_DEPTH=0 \
    SQLITE_OMIT_DEPRECATED=1 \
    SQLITE_OMIT_PROGRESS_CALLBACK=1 \
    SQLITE_OMIT_SHARED_CACHE=1